#BSUB -W 1:00
#BSUB -o <path/to/my/logs>
#BSUB -cwd <path/to/my/working/directory>
#BSUB -q short
#BSUB -n 12
#BSUB -M 17
#BSUB -R rusage[mem=17]
#BSUB -u <your-email-address>
#BSUB -J variant-call-family

for FILE in *.bam; do
        while ["$(jobs -p | wc -l)" -ge "SLURM_NTASKS"]; do
                sleep 30
        done

        singularity exec gatk.sif_latest.sif --java-options "-Djava.io.tmpdir=/tmp/$SLURM_JOBID -Xms20G -Xmx20G -XX:ParallelGCThreads=2" HaplotypeCaller \
                -R ./Homo_sapiens_assembly19.fasta \
                -I $FILE \
                -O "{FILE%.bam}.g.vcf"

        singularity exec gatk.sif_latest.sif --java-options "-Djava.io.tmpdir=/tmp/$SLURM_JOBID -Xms20G -Xmx20G -XX:ParallelGCThreads=2" HaplotypeCaller \
                -R Homo_sapiens_assembly19.fasta \
                -I $FILE \
                -O "${FILE%.bam}.g.vcf";
done
wait

for FILE in *.bam; do
        while ["$(jobs -p | wc -l)" -ge "SLURM_NTASKS"]; do
                sleep 30
        done

        singularity exec gatk.sif_latest.sif --java-options "-Djava.io.tmpdir=/tmp/$SLURM_JOBID -Xms20G -Xmx20G -XX:ParallelGCThreads=2" GenotypeGVCFs \
                -R data/ref/ref.fasta \
                -V gendb://my_database \
                -O output.g.vcf

done
wait
